services:
  - type: web
    name: budget-tracker-backend
    runtime: python3
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        fromDatabase:
          name: budget-tracker-db
          property: connectionString
      - key: MONGODB_DB_NAME
        value: budget_tracker
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://budget-tracker.jbbru.com,https://budget.jbbru.com,https://jbbru.com,http://localhost:3000"

databases:
  - name: budget-tracker-db
    plan: free
